//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DEDUCCIONE
    {
        public int id { get; set; }
        public int idUsuario { get; set; }
        public int idNomina { get; set; }
        public string detalle { get; set; }
        public decimal monto { get; set; }
    
        public virtual NOMINA NOMINA { get; set; }
        public virtual NOMINA NOMINA1 { get; set; }
        public virtual USUARIO USUARIO { get; set; }
        public virtual USUARIO USUARIO1 { get; set; }
    }
}
