//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EVALUACION
    {
        public int id { get; set; }
        public int idEmpleado { get; set; }
        public int idPeriodo { get; set; }
        public int notaPromedio { get; set; }
        public string retroalimentacion { get; set; }
        public System.DateTime fechaEvaluacion { get; set; }
        public int idEvaluador { get; set; }
    
        public virtual USUARIO USUARIO { get; set; }
        public virtual USUARIO USUARIO1 { get; set; }
        public virtual PERIODO PERIODO { get; set; }
    }
}
