//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto2.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BONIFICACIONE> BONIFICACIONES { get; set; }
        public virtual DbSet<DEDUCCIONE> DEDUCCIONES { get; set; }
        public virtual DbSet<DEPARTAMENTO> DEPARTAMENTOes { get; set; }
        public virtual DbSet<EVALUACION> EVALUACIONs { get; set; }
        public virtual DbSet<EVENTO> EVENTOes { get; set; }
        public virtual DbSet<METODO_PAGO> METODO_PAGO { get; set; }
        public virtual DbSet<MODULO> MODULOes { get; set; }
        public virtual DbSet<NOMINA> NOMINAs { get; set; }
        public virtual DbSet<OBJETIVO> OBJETIVOS { get; set; }
        public virtual DbSet<OPERACIONE> OPERACIONES { get; set; }
        public virtual DbSet<PERIODO> PERIODOes { get; set; }
        public virtual DbSet<PUESTO> PUESTOes { get; set; }
        public virtual DbSet<ROL> ROLs { get; set; }
        public virtual DbSet<ROL_OPERACION> ROL_OPERACION { get; set; }
        public virtual DbSet<TURNO> TURNOes { get; set; }
        public virtual DbSet<USUARIO> USUARIOs { get; set; }
        public virtual DbSet<USUARIO_OPERACIONES> USUARIO_OPERACIONES { get; set; }
    }
}
