//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NOMINA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NOMINA()
        {
            this.BONIFICACIONES = new HashSet<BONIFICACIONE>();
            this.DEDUCCIONES = new HashSet<DEDUCCIONE>();
            this.DEDUCCIONES1 = new HashSet<DEDUCCIONE>();
        }
    
        public int id { get; set; }
        public int idUsuario { get; set; }
        public int ano { get; set; }
        public int mes { get; set; }
        public int estado { get; set; }
        public int idMetodoPago { get; set; }
        public decimal salarioBase { get; set; }
        public decimal bonificacionesTotal { get; set; }
        public decimal deduccionesTotal { get; set; }
        public decimal salarioNeto { get; set; }
        public string comentario { get; set; }
        public System.DateTime fechaRegistro { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BONIFICACIONE> BONIFICACIONES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DEDUCCIONE> DEDUCCIONES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DEDUCCIONE> DEDUCCIONES1 { get; set; }
        public virtual METODO_PAGO METODO_PAGO { get; set; }
        public virtual USUARIO USUARIO { get; set; }
    }
}
