//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TURNO
    {
        public int id { get; set; }
        public int idEmpleado { get; set; }
        public string dias { get; set; }
        public string horaEntrada { get; set; }
        public string horaSalida { get; set; }
        public System.DateTime fechaRegistro { get; set; }
        public int idEncargado { get; set; }
    
        public virtual USUARIO USUARIO { get; set; }
        public virtual USUARIO USUARIO1 { get; set; }
    }
}
