//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class USUARIO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public USUARIO()
        {
            this.BONIFICACIONES = new HashSet<BONIFICACIONE>();
            this.DEDUCCIONES = new HashSet<DEDUCCIONE>();
            this.DEDUCCIONES1 = new HashSet<DEDUCCIONE>();
            this.EVALUACIONs = new HashSet<EVALUACION>();
            this.EVALUACIONs1 = new HashSet<EVALUACION>();
            this.NOMINAs = new HashSet<NOMINA>();
            this.OBJETIVOS = new HashSet<OBJETIVO>();
            this.OBJETIVOS1 = new HashSet<OBJETIVO>();
            this.TURNOes = new HashSet<TURNO>();
            this.TURNOes1 = new HashSet<TURNO>();
            this.USUARIO_OPERACIONES = new HashSet<USUARIO_OPERACIONES>();
        }
    
        public int id { get; set; }
        public string nombre { get; set; }
        public string apellido { get; set; }
        public string email { get; set; }
        public string contrasena { get; set; }
        public System.DateTime fechaCreacion { get; set; }
        public int idRol { get; set; }
        public string direccion { get; set; }
        public int telefono { get; set; }
        public System.DateTime fechaNacimiento { get; set; }
        public int idGenero { get; set; }
        public string nacionalidad { get; set; }
        public int idDepartamento { get; set; }
        public int idPuesto { get; set; }
        public System.DateTime fechaUnion { get; set; }
        public int salarioBase { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BONIFICACIONE> BONIFICACIONES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DEDUCCIONE> DEDUCCIONES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DEDUCCIONE> DEDUCCIONES1 { get; set; }
        public virtual DEPARTAMENTO DEPARTAMENTO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EVALUACION> EVALUACIONs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EVALUACION> EVALUACIONs1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NOMINA> NOMINAs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OBJETIVO> OBJETIVOS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OBJETIVO> OBJETIVOS1 { get; set; }
        public virtual PUESTO PUESTO { get; set; }
        public virtual ROL ROL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TURNO> TURNOes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TURNO> TURNOes1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<USUARIO_OPERACIONES> USUARIO_OPERACIONES { get; set; }
    }
}
